%YAML:1.0
---
imageScaling: 2.0000000000000001e-01
gridWidth: 4
gridHeight: 4
ballSettings:
   hueMax: 114
   satMax: 255
   valMax: 255
   hueMin: 107
   satMin: 184
   valMin: 0
   erosions: 0
   dilations: 6
   gridPercentage: 20
bgSettings:
   hueMax: 179
   satMax: 45
   valMax: 255
   hueMin: 0
   satMin: 0
   valMin: 0
   erosions: 0
   dilations: 0
   gridPercentage: 20
